---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Update apt-get repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install packages only when the apt process is not locked
      apt:
        name: apt
        state: present
        force_apt_get: yes
      register: apt_action
      retries: 100
      until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

    - name: Upgrade all apt packages
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Check if a reboot is needed
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Reboot servers not ansible host
      reboot:
        msg: "Reboot initiated by Ansible due to updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: (reboot_required_file.stat.exists) and not ("'foras' in inventory_hostname")

    - name: Reboot ansible host delayed
      reboot:
        msg: "Reboot initiated by Ansible due to updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 1800
        post_reboot_delay: 30
        test_command: uptime
      when: (reboot_required_file.stat.exists) and ("'foras' in inventory_hostname")
