---
- hosts: all
  tasks:
    - name: Add tailscale apt GPG key
      become: true
      apt_key:
        url: 'https://pkgs.tailscale.com/stable/ubuntu/focal.gpg'

    - name: Add tailscale apt list
      become: true
      apt_repository:
        repo: 'deb https://pkgs.tailscale.com/stable/ubuntu focal main'

    - name: apt update tailscale
      become: true
      apt:
        state: latest
        update_cache: true
        name:
          - tailscale
